### ISSUE TITLE
replay: Failing because it cannot find asset

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/vega-market-sim#191]
Replaying saved transactions:
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/62546419/194081319-d7f95fce-c64d-4c96-a35e-9a6039639c57.png">
When I check on the data node 
```
{
  party(id:"1247e68a5e63d8d5867099107503ec6eb830a88767f249c61a76a91b766e75c5") 
	{
    id
    accountsConnection {
      edges {
        node  {
          asset {
            id
          }
          balance
        }
      }
    }
  }
}
``` 
I see the party does have just the vote asset:
```
{
  "data": {
    "party": {
      "id": "1247e68a5e63d8d5867099107503ec6eb830a88767f249c61a76a91b766e75c5",
      "accountsConnection": {
        "edges": [
          {
            "node": {
              "asset": {
                "id": "VOTE"
              },
              "balance": "1000000000"
            }
          }
        ]
      }
    }
  }
}
```
The python crash log is: 
```
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/davidsiska/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/Users/davidsiska/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/davidsiska/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/davidsiska/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/davidsiska/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/davidsiska/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/vega_sim/reinforcement/replay.py", line 9, in <module>
    with replay.replay_run_context(retain_log_files=True,replay_path=log_dir) as vega:
  File "/opt/miniconda3/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/vega_sim/replay/replay.py", line 60, in replay_run_context
    curr_acct = party_account(
  File "/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/vega_sim/api/data.py", line 243, in party_account
    asset_dp if asset_dp is not None else asset_decimals(asset_id, data_client)
  File "/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/vega_sim/api/data.py", line 351, in asset_decimals
    return data_raw.asset_info(
  File "/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/vega_sim/api/data_raw.py", line 101, in asset_info
    return data_client.AssetByID(
  File "/Users/davidsiska/Library/Caches/pypoetry/virtualenvs/vega-sim-L42lfpJQ-py3.10/lib/python3.10/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/davidsiska/Library/Caches/pypoetry/virtualenvs/vega-sim-L42lfpJQ-py3.10/lib/python3.10/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.NOT_FOUND
        details = "NotFound error"
        debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::1%5D:51042 {created_time:"2022-10-05T15:04:18.222549+01:00", grpc_status:5, grpc_message:"NotFound error"}"
```

**Comment by davidsiska-vega** [comment]
Launched with 
```
import time

from vega_sim.null_service import VegaServiceNull
from vega_sim.replay import replay


if __name__ == "__main__":
    log_dir="/var/folders/67/mjxp58z56yj83_1x0372gkwr0000gn/T/vega-sim-gvsbyhf7/"
    with replay.replay_run_context(retain_log_files=True,replay_path=log_dir) as vega:
        time.sleep(1)
        vega.wait_for_core_catchup()    

    print("All done.")
```

**Comment by TomMcL** [comment]
Should be resolved now
