### ISSUE TITLE
Div by zero in agents._scale_orders

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/vega-market-sim#333]
```[2023-02-12T04:58:24.568Z] INFO:__main__:Running iteration 446

[2023-02-12T04:58:24.568Z] INFO:vega_sim.environment.environment:Running wallet at: http://localhost:54301/

[2023-02-12T04:58:24.568Z] INFO:vega_sim.environment.environment:Running graphql at: http://localhost:50771/

[2023-02-12T04:58:29.067Z] Traceback (most recent call last):

[2023-02-12T04:58:29.067Z]   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main

[2023-02-12T04:58:29.067Z]     return _run_code(code, main_globals, None,

[2023-02-12T04:58:29.067Z]   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code

[2023-02-12T04:58:29.067Z]     exec(code, run_globals)

[2023-02-12T04:58:29.067Z]   File "/vega_market_sim/vega_sim/reinforcement/run_rl_agent.py", line 276, in <module>

[2023-02-12T04:58:29.067Z]     _run(

[2023-02-12T04:58:29.067Z]   File "/vega_market_sim/vega_sim/reinforcement/run_rl_agent.py", line 160, in _run

[2023-02-12T04:58:29.067Z]     _ = run_iteration(

[2023-02-12T04:58:29.067Z]   File "/vega_market_sim/vega_sim/reinforcement/run_rl_agent.py", line 74, in run_iteration

[2023-02-12T04:58:29.067Z]     scenario.env.run(

[2023-02-12T04:58:29.067Z]   File "/vega_market_sim/vega_sim/environment/environment.py", line 150, in run

[2023-02-12T04:58:29.067Z]     return self._run(self._vega, pause_at_completion=pause_at_completion)

[2023-02-12T04:58:29.067Z]   File "/vega_market_sim/vega_sim/environment/environment.py", line 198, in _run

[2023-02-12T04:58:29.067Z]     self.step(vega)

[2023-02-12T04:58:29.067Z]   File "/vega_market_sim/vega_sim/environment/environment.py", line 371, in step

[2023-02-12T04:58:29.067Z]     agent.step(state)

[2023-02-12T04:58:29.067Z]   File "/vega_market_sim/vega_sim/scenario/common/agents.py", line 1177, in step

[2023-02-12T04:58:29.067Z]     scaled_buy_shape, scaled_sell_shape = self._scale_orders(

[2023-02-12T04:58:29.067Z]   File "/vega_market_sim/vega_sim/scenario/common/agents.py", line 1259, in _scale_orders

[2023-02-12T04:58:29.067Z]     buy_scaling_factor = (

[2023-02-12T04:58:29.067Z] ZeroDivisionError: float division by zero
```

**Comment by cdummett** [comment]
`_calculate_liquidity` doesn't consider orders with a negative price when calculating the liquidity (correct behaviour). If all the orders of the MM have a negative price, the `provided_liquidity=0` which raises the `ZeroDivisionError` later.

For the MM to generate a shape or orders all of which have a negative price, the following must be true:

```
current_external_price - optimal_bid_depth < 0
```

 Since `random_walk` re-generates any price process which gives a single negative price, for the MM to generate a shape of all negative prices, the `random_walk` method must generate a price process with the following conditions:

```
all(S > 0) and any(S < max(optimal_bid_depths))
```

So with the current RL scenario setup, a ~0.059% chance! Explains why it doesn't come up in any other RL runs.

![monte](https://user-images.githubusercontent.com/99198652/219757982-f69628e1-1114-4ba9-a15c-25f699a0316f.png)
