### ISSUE TITLE
bug: successor market proposals failing in overnight runs

### ISSUE THREAD

**Issue by cdummett** [vegaprotocol/vega-market-sim#482]
In overnight fuzz tests after multiple successive children market-sim new market proposal fails:

Can be reproduced locally with:
```
python -m vega_sim.scenario.fuzzed_markets.run_fuzz_test -s 2440
```

```
2023-08-09 00:31:09,972 - root - INFO - Removing volume 7d7c728610dfa77f9ad68f2c1264b38fbdcf96c19318368699af54bebc083fba

Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "/jenkins/workspace/common/vega-market-sim-reinforcement/vega_sim/scenario/fuzzed_markets/run_fuzz_test.py", line 95, in <module>

    _run(steps=args.steps, console=args.console, output=True)

  File "/jenkins/workspace/common/vega-market-sim-reinforcement/vega_sim/scenario/fuzzed_markets/run_fuzz_test.py", line 44, in _run

    scenario.run_iteration(

  File "/jenkins/workspace/common/vega-market-sim-reinforcement/vega_sim/scenario/scenario.py", line 102, in run_iteration

    outputs = self.env.run(

              ^^^^^^^^^^^^^

  File "/jenkins/workspace/common/vega-market-sim-reinforcement/vega_sim/environment/environment.py", line 166, in run

    return self._run(

           ^^^^^^^^^^

  File "/jenkins/workspace/common/vega-market-sim-reinforcement/vega_sim/environment/environment.py", line 236, in _run

    self.step(vega)

  File "/jenkins/workspace/common/vega-market-sim-reinforcement/vega_sim/environment/environment.py", line 420, in step

    agent.step(state)

  File "/jenkins/workspace/common/vega-market-sim-reinforcement/vega_sim/scenario/fuzzed_markets/agents.py", line 844, in step

    self._create_latest_market(parent_market_id=self.market_id)

  File "/jenkins/workspace/common/vega-market-sim-reinforcement/vega_sim/scenario/fuzzed_markets/agents.py", line 799, in _create_latest_market

    self.vega.create_market_from_config(

  File "/jenkins/workspace/common/vega-market-sim-reinforcement/vega_sim/service.py", line 502, in create_market_from_config

    proposal_id = gov.propose_market_from_config(

                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/jenkins/workspace/common/vega-market-sim-reinforcement/vega_sim/api/governance.py", line 129, in propose_market_from_config

    return _make_and_wait_for_proposal(

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/jenkins/workspace/common/vega-market-sim-reinforcement/vega_sim/api/governance.py", line 544, in _make_and_wait_for_proposal

    raise ProposalNotAcceptedError(

vega_sim.api.helpers.ProposalNotAcceptedError: Your proposal was STATE_REJECTED due to PROPOSAL_ERROR_INVALID_SUCCESSOR_MARKET. Any further info: market to succeed does not exist
```

**Comment by cdummett** [comment]
Closed as stale issue and no longer an active bug.
